---
- name: Create my user with all privileges
  mysql_user:
    name: me_kiran
    host: '%'
    password: kiran
    priv: "*.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create monitoring user with only read privileges
  mysql_user:
    name: monitoring
    host: '%'
    password: kiran
    priv: "*.*:SELECT"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock