---
- name: Ensure replication user exists on master else create it
  mysql_user:
    name: "kmaster"
    host: "%"
    password: "kiran"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: ansible_enp0s8.ipv4.address == groups['master_node'][0]

#get gtid_binlog_pos value from master as gtid[2]
- name: Get the gtid of gtid_binlog_pos
  command: /usr/bin/mysql -u root -e "show global variables like 'gtid_binlog_pos'"
  register: gtid_str
  when: ansible_enp0s8.ipv4.address == groups['master_node'][0]
# - debug: var=gtid_str.stdout
#   when: ansible_enp0s8.ipv4.address == groups['master_node'][0]
- set_fact:
    gtid: "{{ gtid_str.stdout.split('\t') }}"
  when: ansible_enp0s8.ipv4.address == groups['master_node'][0]
# - debug: var=hostvars['172.10.10.202']['gtid'][1]
- name: stop slave on slave node
  command: /usr/bin/mysql -u root -e "STOP SLAVE"
  when: ansible_enp0s8.ipv4.address == groups['slave_node'][0]

- name: get global gtid_slave_pos value
  command: /usr/bin/mysql -u root -e "show global variables like 'gtid_slave_pos'"
  register: slave_stat
  when: ansible_enp0s8.ipv4.address == groups['slave_node'][0]

- set_fact:
    s_pos: "{{ slave_stat.stdout.split('\t') }}"
  when: ansible_enp0s8.ipv4.address == groups['slave_node'][0]

- name: declare the slave_pos global variable
  command: /usr/bin/mysql -u root -e "SET GLOBAL gtid_slave_pos = '{{ hostvars['172.10.10.202']['gtid'][2] }}'"
  when: 
    - ansible_enp0s8.ipv4.address == groups['slave_node'][0]
    - s_pos.2 is not defined

- name: configuring replication in slave using shell command
  command: /usr/bin/mysql -u root -e "CHANGE MASTER TO MASTER_HOST='172.10.10.202', MASTER_USER='kmaster', MASTER_PASSWORD='kiran', MASTER_USE_GTID=slave_pos";
  when: ansible_enp0s8.ipv4.address == groups['slave_node'][0]

- name: start slave on slave node
  command: /usr/bin/mysql -u root -e "START SLAVE"
  when: ansible_enp0s8.ipv4.address == groups['slave_node'][0]

#stop server on slave node
- name: Stop MariaDB on slave node
  service: name=mariadb state=stopped
  when: ansible_enp0s8.ipv4.address == groups['slave_node'][0]

# - name: Remove galera.cnf in slave-node
#   ansible.builtin.file:
#     path: /etc/mysql/conf.d/galera.cnf
#     state: absent
#   when: ansible_enp0s8.ipv4.address == groups['slave_node'][0]

- name: Switch off wsrep on slave node
  replace:
    path: /etc/mysql/conf.d/galera.cnf
    regexp: 'wsrep_on=ON'
    replace: 'wsrep_on=OFF'
  when: 
    - ansible_enp0s8.ipv4.address == groups['slave_node'][0]

#start the servers on slave node
- name: Start MariaDB on slave node
  service: name=mariadb state=started
  when: ansible_enp0s8.ipv4.address == groups['slave_node'][0]