---
- name: Get Nodes Names and IPs
  remote_user: kiran
  hosts: nodes
  serial: 1
  tasks:
    - name: Node Names
      command: hostname
      register: output1
    - name: output_write_node_name
      lineinfile:
        dest: /home/kiran/Documents/output
        line: "{{ output1.stdout }}"
        insertafter: EOF
      delegate_to: localhost
    - name: Node IPs
      command: hostname -I
      register: output2
    - name: output_write_node_ip
      lineinfile:
        dest: /home/kiran/Documents/output
        line: "{{ output2.stdout }}"
        insertafter: EOF
      delegate_to: localhost